export const TYPES = {
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  SET_ACTIVE: "SET_ACTIVE",
  ADD_TASK: "ADD_TASK",
  CHECK_TASK: "CHECK_TASK",
  DELETE_TASK: "DELETE_TASK",
  DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
  DELETE_ALL_TASKS: "DELETE_ALL_TASKS",
  EDIT_TITLE: "EDIT_TITLE",
};
